name: Build and Push Docker Image

on:
  push:
    branches:
      - master  # Trigger the workflow on push to the 'main' branch

jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up Docker Buildx (required for multi-platform builds, optional)
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Log in to Docker Hub or GitHub Container Registry
    - name: Log in to Registry
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.REGISTRY_USERNAME }}  # Add your Docker Hub username to secrets
        password: ${{ secrets.REGISTRY_PASSWORD }}  # Add your Docker Hub password to secrets

    # Build the Docker image
    - name: Build Docker image
      run: |
        docker build -t ${{ secrets.REGISTRY_URL }}/alpha:${{ github.ref }} .  # Build with the commit hash as the tag
    # Push the Docker image to Docker Hub or another registry
    - name: Push Docker image
      run: |
        docker push ${{ secrets.REGISTRY_URL }}/alpha:${{ github.ref }}  # Push with the commit hash tag
