name: Build and Push Docker Image

on:
  push:
    branches:
      - master  # Trigger the workflow on push to the 'main' branch

jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    environment:
      name: master
  
    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up Docker Buildx (required for multi-platform builds, optional)
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Log in to Docker Hub or GitHub Container Registry
    - name: Log in to Registry
      run: |
        docker login -u='${{ secrets.REGISTRY_USERNAME}}' -p='${{ secrets.REGISTRY_PASSWORD }}' https://${{ secrets.REGISTRY_URL }}

    # Build the Docker image
    - name: Build Docker image
      run: |
        docker build -t ${{ secrets.REGISTRY_URL }}/alpha:master .  # Build with the commit hash as the tag
    # Push the Docker image to Docker Hub or another registry
    - name: Push Docker image
      run: |
        docker push ${{ secrets.REGISTRY_URL }}/alpha:master  # Push with the commit hash tag
        
  rollout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up OpenShift CLI
        run: |
          # Install OpenShift CLI (oc) manually
          curl -Lo oc.tar.gz https://mirror.openshift.com/pub/openshift-v4/clients/oc/latest/openshift-client-linux.tar.gz
          file oc.tar.gz
          tar -xvzf oc.tar.gz
          sudo mv oc /usr/local/bin/
          oc version

      - name: Log in to OpenShift
        env:
          OPENSHIFT_SERVER: ${{ secrets.OPENSHIFT_SERVER }}
          OPENSHIFT_TOKEN: ${{ secrets.OPENSHIFT_TOKEN }}
        run: |
          oc login $OPENSHIFT_SERVER --token=$OPENSHIFT_TOKEN --insecure-skip-tls-verify=true
          
      - name: Trigger rollout
        run: |
          # Replace these with your actual namespace and deployment
          DEPLOYMENT_NAME=d-alpha-fe
          NAMESPACE=single
          
          # Trigger the rollout
          oc rollout restart deployment/$DEPLOYMENT_NAME -n $NAMESPACE
          
      - name: Logout of Openshift
        run: |
          oc logout
